# Generated by Django 5.0.2 on 2024-04-21 00:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('type', models.DecimalField(choices=[(0, 'Offre'), (1, 'Demande')], decimal_places=0, default=1, max_digits=1)),
                ('date', models.DateField(default=datetime.datetime(2024, 4, 21, 0, 17, 8, 62092, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poste.poste')),
                ('intitule', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=60)),
                ('lieu', models.CharField(max_length=30)),
                ('contactInfo', models.CharField(max_length=50)),
            ],
            bases=('poste.poste',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poste.poste')),
                ('localisation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('contactInfo', models.CharField(max_length=50)),
            ],
            bases=('poste.poste',),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poste.poste')),
                ('texte', models.CharField(max_length=250)),
            ],
            bases=('poste.poste',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poste.poste')),
                ('typeStg', models.DecimalField(decimal_places=0, max_digits=1)),
                ('societe', models.CharField(max_length=35)),
                ('duree', models.DecimalField(decimal_places=0, max_digits=1)),
                ('sujet', models.CharField(max_length=200)),
                ('contactInfo', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=60)),
            ],
            bases=('poste.poste',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poste.poste')),
                ('depart', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('hrDep', models.DateTimeField()),
                ('nbSiege', models.DecimalField(decimal_places=0, max_digits=10)),
                ('contactInfo', models.CharField(max_length=50)),
            ],
            bases=('poste.poste',),
        ),
        migrations.CreateModel(
            name='EvenementClub',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poste.evenement')),
                ('club', models.CharField(max_length=20)),
            ],
            bases=('poste.evenement',),
        ),
        migrations.CreateModel(
            name='EvenementSociale',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poste.evenement')),
                ('prix', models.FloatField()),
            ],
            bases=('poste.evenement',),
        ),
    ]
