# Generated by Django 5.0.2 on 2024-04-21 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 21, 0, 21, 48, 564692, tzinfo=datetime.timezone.utc)),
        ),
    ]
