# Generated by Django 5.0.2 on 2024-04-21 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0003_alter_poste_date_alter_stage_typestg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 21, 0, 35, 51, 499377, tzinfo=datetime.timezone.utc)),
        ),
    ]
