# Generated by Django 5.0.2 on 2024-04-21 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0004_alter_poste_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 21)),
        ),
    ]
